import {
  BookOpen,
  Flame,
  Cable,
  Cpu,
  Radio,
  Waves,
  CircuitBoard,
  BarChart3,
  Compass,
  Zap,
  Target,
  Network,
  BookText,
  Boxes,
  Atom,
  GitMerge,
  Merge,
  Sun,
  Layers2,
  Sigma,
  Microscope,
} from 'lucide-react';

export const CHAPTERS = [
  { key: 'WAVE_BASICS', path: '/learn/wave-basics', title: '光波基础与物理量', part: 'Part 1 · 基础篇' },
  { key: 'CRYSTAL_STRUCTURE', path: '/learn/crystal-structure', title: '晶体结构与缺陷', part: 'Part 1 · 基础篇' },
  { key: 'SEMICONDUCTOR_BASICS', path: '/learn/semiconductor-basics', title: '半导体基础', part: 'Part 1 · 基础篇' },
  { key: 'PN_JUNCTION_BASICS', path: '/learn/pn-junction-basics', title: 'PN 结基础', part: 'Part 1 · 基础篇' },
  { key: 'RECOMBINATION', path: '/learn/recombination', title: '载流子复合机制', part: 'Part 1 · 基础篇' },
  { key: 'LIGHT_MATTER_INTERACTION', path: '/learn/light-matter-interaction', title: '光与物质相互作用', part: 'Part 1 · 基础篇' },
  { key: 'HETEROJUNCTION', path: '/learn/heterojunction', title: '异质结与能带对准', part: 'Part 1 · 基础篇' },
  { key: 'SEMICONDUCTOR_EQUATIONS', path: '/learn/semiconductor-equations', title: '半导体基本方程', part: 'Part 1 · 基础篇' },
  { key: 'PN_JUNCTION_ADVANCED', path: '/learn/pn-junction-advanced', title: 'PN 结进阶：暗电流与耗尽区分析', part: 'Part 1 · 基础篇' },
  {
    key: 'OPTOELECTRONIC_MATERIALS',
    path: '/learn/optoelectronic-materials',
    title: '光电效应与光电器件',
    part: 'Part 1 · 基础篇',
  },
  { key: 'LASER', path: '/learn/laser', title: '激光器', part: 'Part 2 · 光源与传输篇' },
  { key: 'FIBER_OPTICS', path: '/learn/fiber-optics', title: '光纤与光波导', part: 'Part 2 · 光源与传输篇' },
  { key: 'MODULATION_BASICS', path: '/learn/modulation-basics', title: '光调制基础', part: 'Part 3 · 调制器篇' },
  { key: 'INTERFERENCE', path: '/learn/interference', title: '干涉原理', part: 'Part 3 · 调制器篇' },
  { key: 'MZ_MODULATOR', path: '/learn/mz-modulator', title: 'MZ 调制器', part: 'Part 3 · 调制器篇' },
  { key: 'IQ_MODULATOR', path: '/learn/iq-modulator', title: 'IQ 调制器', part: 'Part 3 · 调制器篇' },
  { key: 'POLARIZATION', path: '/learn/polarization', title: '偏振复用', part: 'Part 3 · 调制器篇' },
  { key: 'NYQUIST_OFDM', path: '/learn/nyquist-ofdm', title: 'Nyquist 与 OFDM', part: 'Part 3 · 调制器篇' },
  { key: 'PCS_CODING', path: '/learn/pcs-coding', title: '概率星座整形与编码', part: 'Part 3 · 调制器篇' },
  { key: 'RECEIVER', path: '/learn/receiver', title: '光接收器', part: 'Part 4 · 系统篇' },
  { key: 'WDM_AMPLIFIER', path: '/learn/wdm-amplifier', title: 'WDM 与光放大器', part: 'Part 4 · 系统篇' },
  { key: 'SYSTEM_OVERVIEW', path: '/learn/system-overview', title: '完整光通信系统', part: 'Part 4 · 系统篇' },
  { key: 'GLOSSARY', path: '/learn/glossary', title: '术语表', part: '附录' },
] as const;

export const CHAPTER_ICONS = {
  WAVE_BASICS: BookOpen,
  CRYSTAL_STRUCTURE: Boxes,
  SEMICONDUCTOR_BASICS: Atom,
  PN_JUNCTION_BASICS: GitMerge,
  RECOMBINATION: Merge,
  LIGHT_MATTER_INTERACTION: Sun,
  HETEROJUNCTION: Layers2,
  SEMICONDUCTOR_EQUATIONS: Sigma,
  PN_JUNCTION_ADVANCED: Microscope,
  OPTOELECTRONIC_MATERIALS: Cpu,
  LASER: Flame,
  FIBER_OPTICS: Cable,
  MODULATION_BASICS: Radio,
  INTERFERENCE: Waves,
  MZ_MODULATOR: CircuitBoard,
  IQ_MODULATOR: BarChart3,
  POLARIZATION: Compass,
  NYQUIST_OFDM: Zap,
  PCS_CODING: Target,
  RECEIVER: Radio,
  WDM_AMPLIFIER: Network,
  SYSTEM_OVERVIEW: BookOpen,
  GLOSSARY: BookText,
} as const;

export type ChapterKey = (typeof CHAPTERS)[number]['key'];
