export const ROUTES = {
  LEARN: {
    WAVE_BASICS: '/learn/wave-basics',
    CRYSTAL_STRUCTURE: '/learn/crystal-structure',
    SEMICONDUCTOR_BASICS: '/learn/semiconductor-basics',
    PN_JUNCTION_BASICS: '/learn/pn-junction-basics',
    RECOMBINATION: '/learn/recombination',
    LIGHT_MATTER_INTERACTION: '/learn/light-matter-interaction',
    HETEROJUNCTION: '/learn/heterojunction',
    SEMICONDUCTOR_EQUATIONS: '/learn/semiconductor-equations',
    PN_JUNCTION_ADVANCED: '/learn/pn-junction-advanced',
    OPTOELECTRONIC_MATERIALS: '/learn/optoelectronic-materials',
    LASER: '/learn/laser',
    FIBER_OPTICS: '/learn/fiber-optics',
    MODULATION_BASICS: '/learn/modulation-basics',
    INTERFERENCE: '/learn/interference',
    MZ_MODULATOR: '/learn/mz-modulator',
    IQ_MODULATOR: '/learn/iq-modulator',
    POLARIZATION: '/learn/polarization',
    NYQUIST_OFDM: '/learn/nyquist-ofdm',
    PCS_CODING: '/learn/pcs-coding',
    RECEIVER: '/learn/receiver',
    WDM_AMPLIFIER: '/learn/wdm-amplifier',
    SYSTEM_OVERVIEW: '/learn/system-overview',
    GLOSSARY: '/learn/glossary',
  },
  PLAYGROUND: {
    INTERFERENCE: '/playground/interference',
    MZ_MODULATOR: '/playground/mz-modulator',
    IQ_MODULATOR: '/playground/iq-modulator',
    POLARIZATION: '/playground/polarization',
    RECEIVER: '/playground/receiver',
  },
} as const;
